# Tarefa 

#### 1)  crie uma série do pandas a partir de uma lista com os dados abaixo:

Em um estudo sobre alteração na temperatura global, A NASA disponibiliza dados de diferenças de temperatura média da superfície terrestre relativos às médias de temperatura entre 1951 e 1980. Os dados originais podem ser vistos no site da NASA/GISS, e estão dispostos a cada década na tabela abaixo:

|ano|anomalia termica|
|:-:|:----:|
| 1900 | -0.08 |
| 1920 | -0.27 |
| 1940 | 0.12 |
| 1960 | -0.03 |
| 1980 | 0.26 |
| 2000 | 0.40 |
| 2020 | 1.02 |

Crie uma séries do Pandas a partir de uma lista com esses dados.

In [36]:
import pandas as pd
import numpy as np

lista_ano = [1900,1920,1940,1960,1980,2000,2020]
lista_anomalia_termica = [-0.08,-0.27,0.12,-0.03,0.26,0.40,1.02]

serie_ano = pd.Series(lista_ano)
serie_anomalia_termica = pd.Series(lista_anomalia_termica)

print(serie_ano)
print('\n')
print(serie_anomalia_termica)

0    1900
1    1920
2    1940
3    1960
4    1980
5    2000
6    2020
dtype: int64


0   -0.08
1   -0.27
2    0.12
3   -0.03
4    0.26
5    0.40
6    1.02
dtype: float64


#### 2) Coloque os anos nos índices conforme a tabela.

In [42]:
serie_anomalia = pd.Series(lista_anomalia_termica, index=lista_ano)
print(serie_anomalia)

1900   -0.08
1920   -0.27
1940    0.12
1960   -0.03
1980    0.26
2000    0.40
2020    1.02
dtype: float64


#### 3) A partir do dicionário abaixo, crie uma séries do Pandas:

In [46]:
dic_temperaturas = {1900: -.08, 1920: -.27, 1940: .12, 1960: -.03, 1980: .26, 2000: .40, 2020: 1.02}
teste = pd.Series(dic_temperaturas)
print(teste)

1900   -0.08
1920   -0.27
1940    0.12
1960   -0.03
1980    0.26
2000    0.40
2020    1.02
dtype: float64


#### 4) Transforme o ndarray abaixo em um dataframe. 
O numpy é capaz de gerar arrays n-dimensionais com números pseudo-aleatórios de acordo com uma variedade de distribuições, como no exemplo abaixo. Transforme esse nd-array em um DataFrame.

In [67]:
array = np.round(np.random.normal(100, 10, (20,3)),2)
print(array)

df_array = pd.DataFrame(array)

[[103.54  98.93 111.2 ]
 [112.99 100.03 107.97]
 [107.15  91.92  81.32]
 [ 84.86 102.22  95.66]
 [ 99.89  91.78  85.48]
 [112.18 100.01 104.2 ]
 [ 96.52 104.37  91.18]
 [ 89.99 110.24  98.78]
 [ 94.45 100.71  87.2 ]
 [ 95.21  87.24 104.39]
 [ 91.38  92.39  90.16]
 [ 94.6   79.54  98.98]
 [ 96.73  94.02  83.83]
 [ 97.09  95.56 110.79]
 [ 88.94  94.99 103.78]
 [ 96.85  96.02 109.47]
 [112.77 104.77  95.33]
 [ 98.28 104.5   97.62]
 [ 81.64  96.66 105.05]
 [ 88.55  89.74 100.36]]


#### 5) Nomeie os índices das linhas com inteiros de 1 a 20, e as colunas com os nomes "x1", "x2", e "x3" respectivamente.

In [71]:
df_array_com_indices = pd.DataFrame(array, columns=['x1','x2','x3'], index=range(1,21))
print(df_array_com_indices)

        x1      x2      x3
1   103.54   98.93  111.20
2   112.99  100.03  107.97
3   107.15   91.92   81.32
4    84.86  102.22   95.66
5    99.89   91.78   85.48
6   112.18  100.01  104.20
7    96.52  104.37   91.18
8    89.99  110.24   98.78
9    94.45  100.71   87.20
10   95.21   87.24  104.39
11   91.38   92.39   90.16
12   94.60   79.54   98.98
13   96.73   94.02   83.83
14   97.09   95.56  110.79
15   88.94   94.99  103.78
16   96.85   96.02  109.47
17  112.77  104.77   95.33
18   98.28  104.50   97.62
19   81.64   96.66  105.05
20   88.55   89.74  100.36


#### 6) No DataFrame do exercício 5, crie uma nova coluna como sendo a média das três colunas, e dê a ela o nome de "media" (não recomendo colocar acentos em nomes de variáveis).

In [81]:
lista_medias = (df_array_com_indices['x1'] + df_array_com_indices['x2'] + df_array_com_indices['x3']) / 3
df_array_com_indices['media'] = lista_medias
print(df_array_com_indices)

        x1      x2      x3       media
1   103.54   98.93  111.20  104.556667
2   112.99  100.03  107.97  106.996667
3   107.15   91.92   81.32   93.463333
4    84.86  102.22   95.66   94.246667
5    99.89   91.78   85.48   92.383333
6   112.18  100.01  104.20  105.463333
7    96.52  104.37   91.18   97.356667
8    89.99  110.24   98.78   99.670000
9    94.45  100.71   87.20   94.120000
10   95.21   87.24  104.39   95.613333
11   91.38   92.39   90.16   91.310000
12   94.60   79.54   98.98   91.040000
13   96.73   94.02   83.83   91.526667
14   97.09   95.56  110.79  101.146667
15   88.94   94.99  103.78   95.903333
16   96.85   96.02  109.47  100.780000
17  112.77  104.77   95.33  104.290000
18   98.28  104.50   97.62  100.133333
19   81.64   96.66  105.05   94.450000
20   88.55   89.74  100.36   92.883333


#### 7) No DataFrame do exercício 6, crie uma nova coluna chamada "log_med", contendo o logaritmo natural da média calculada no exercício 6 <br>

In [99]:
lista_logaritmos = np.log(df_array_com_indices['media'])
df_array_com_indices['log_med'] = lista_logaritmos
print(df_array_com_indices)
print('\n')
print(df_array_com_indices.describe())

        x1      x2      x3       media   log_med
1   103.54   98.93  111.20  104.556667  4.649729
2   112.99  100.03  107.97  106.996667  4.672798
3   107.15   91.92   81.32   93.463333  4.537569
4    84.86  102.22   95.66   94.246667  4.545915
5    99.89   91.78   85.48   92.383333  4.525947
6   112.18  100.01  104.20  105.463333  4.658363
7    96.52  104.37   91.18   97.356667  4.578381
8    89.99  110.24   98.78   99.670000  4.601865
9    94.45  100.71   87.20   94.120000  4.544571
10   95.21   87.24  104.39   95.613333  4.560312
11   91.38   92.39   90.16   91.310000  4.514260
12   94.60   79.54   98.98   91.040000  4.511299
13   96.73   94.02   83.83   91.526667  4.516630
14   97.09   95.56  110.79  101.146667  4.616572
15   88.94   94.99  103.78   95.903333  4.563341
16   96.85   96.02  109.47  100.780000  4.612940
17  112.77  104.77   95.33  104.290000  4.647175
18   98.28  104.50   97.62  100.133333  4.606503
19   81.64   96.66  105.05   94.450000  4.548071
20   88.55   89.74  